# Overall play time, across all roles.
# This tracker must exist, it is used directly by PlayTimeTrackingManager
- type: playTimeTracker
  id: Overall

# Xenos
- type: playTimeTracker
  id: XenoOverall

- type: playTimeTracker
  id: RoleXenoDrone

- type: playTimeTracker
  id: RoleXenoRunner

- type: playTimeTracker
  id: RoleXenoSentinel

- type: playTimeTracker
  id: RoleXenoDefender

- type: playTimeTracker
  id: RoleXenoQueen


# Marines

- type: playTimeTracker
  id: MarineOverall

- type: playTimeTracker
  id: RoleMarineSquadLeader
